stages:      
  - build
  - test
  - deploy

build-job: 
  stage: build
  script:
    - docker build -t my-bot-image .

# build-test: 
#   stage: test
#   script:
#     - docker run --rm my-bot-image gotest -s -v

build-deploy: 
  stage: deploy
  script:
    - docker compose up --d
